export const ADMIN_REQUEST="ADMIN_REQUEST"
export const ADMIN_ERROR="ADMIN_ERROR"
export const GET_ADMIN_SUCESS="GET_ADMIN_SUCESS"
export const POST_ADMIN_SUCESS="POST_ADMIN_SUCESS"



export const WINTER_DATA_REQUEST = "WINTER_DATA_REQUEST";
export const WINTER_DATA_SUCCESS = "WINTER_DATA_SUCCESS";
export const WINTER_DATA_FAILURE = "WINTER_DATA_FAILURE";


export const SINGLE_PRODUCT_DATA_REQUEST = "SINGLE_PRODUCT_DATA_REQUEST";
export const SINGLE_PRODUCT_DATA_SUCCESS = "SINGLE_PRODUCT_DATA_SUCCESS";
export const SINGLE_PRODUCT_DATA_FAILURE = "SINGLE_PRODUCT_DATA_FAILURE";


export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_REMOVES = "ADD_TO_CART_REMOVES"
export const CART_SAVE_SHIPPING_ADDRESS= "CART_SAVE_SHIPPING_ADDRESS"


export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE";

export const QUANTITY_CHANGE_SUCCESS = "QUANTITY_CHANGE_SUCCESS";
export const CART_PAGE_TOTAL_AMOUNT = "CART_PAGE_TOTAL_AMOUNT";
export const CART_PAGE_TOTAL_ITEMS = "CART_PAGE_TOTAL_ITEMS";
export const APPLY_COUPON_DISCOUNT = "APPLY_COUPON_DISCOUNT";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS= "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL= "USER_LOGIN_FAIL"

export const USER_LOGIN_LOGOUT= "USER_LOGIN_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS= "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL= "USER_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS= "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL= "USER_DETAILS_FAIL"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS= "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL= "USER_UPDATE_FAIL"


export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";


export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL"