export const ADMIN_REQUEST="ADMIN_REQUEST"
export const ADMIN_ERROR="ADMIN_ERROR"
export const GET_ADMIN_SUCESS="GET_ADMIN_SUCESS"
export const POST_ADMIN_SUCESS="POST_ADMIN_SUCESS"



export const WINTER_DATA_REQUEST = "WINTER_DATA_REQUEST";
export const WINTER_DATA_SUCCESS = "WINTER_DATA_SUCCESS";
export const WINTER_DATA_FAILURE = "WINTER_DATA_FAILURE";


export const SINGLE_PRODUCT_DATA_REQUEST = "SINGLE_PRODUCT_DATA_REQUEST";
export const SINGLE_PRODUCT_DATA_SUCCESS = "SINGLE_PRODUCT_DATA_SUCCESS";
export const SINGLE_PRODUCT_DATA_FAILURE = "SINGLE_PRODUCT_DATA_FAILURE";


export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE";

export const QUANTITY_CHANGE_SUCCESS = "QUANTITY_CHANGE_SUCCESS";
export const CART_PAGE_TOTAL_AMOUNT = "CART_PAGE_TOTAL_AMOUNT";
export const CART_PAGE_TOTAL_ITEMS = "CART_PAGE_TOTAL_ITEMS";
export const APPLY_COUPON_DISCOUNT = "APPLY_COUPON_DISCOUNT";
